//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal
    {
        public int Id { get; set; }
        public string PortalName { get; set; }
        public string PortalHyperLink { get; set; }
        public string PortalDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
