/*
Deployment script for C:\MANGESH\SOURCE\TEST1\DEMOPORTAL\DEMOPORTAL\APP_DATA\DEMOPORTAL.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\MANGESH\SOURCE\TEST1\DEMOPORTAL\DEMOPORTAL\APP_DATA\DEMOPORTAL.MDF"
:setvar DefaultFilePrefix "C_\MANGESH\SOURCE\TEST1\DEMOPORTAL\DEMOPORTAL\APP_DATA\DEMOPORTAL.MDF_"
:setvar DefaultDataPath "C:\Users\swapna\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\swapna\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping unnamed constraint on [dbo].[Portals]...';


GO
ALTER TABLE [dbo].[Portals] DROP CONSTRAINT [DF__Portals__CreateD__239E4DCF];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[Portals]...';


GO
ALTER TABLE [dbo].[Portals] DROP CONSTRAINT [DF__Portals__Created__24927208];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[Portals]...';


GO
ALTER TABLE [dbo].[Portals] DROP CONSTRAINT [DF__Portals__Modifed__25869641];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping unnamed constraint on [dbo].[Portals]...';


GO
ALTER TABLE [dbo].[Portals] DROP CONSTRAINT [DF__Portals__Modifie__267ABA7A];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[Portals]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Portals] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [PortalName]        NVARCHAR (100) NULL,
    [PortalHyperLink]   NVARCHAR (256) NULL,
    [PortalDescription] NVARCHAR (500) NULL,
    [CreateDate]        DATETIME       DEFAULT (getdate()) NULL,
    [CreatedBy]         NVARCHAR (256) DEFAULT (suser_sname()) NULL,
    [ModifedBy]         NVARCHAR (256) DEFAULT (suser_sname()) NULL,
    [ModifiedDate]      DATETIME       DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Portals])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Portals] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Portals] ([Id], [PortalName], [PortalHyperLink], [PortalDescription], [CreateDate], [CreatedBy], [ModifedBy], [ModifiedDate])
        SELECT   [Id],
                 [PortalName],
                 [PortalHyperLink],
                 [PortalDescription],
                 [CreateDate],
                 [CreatedBy],
                 [ModifedBy],
                 [ModifiedDate]
        FROM     [dbo].[Portals]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Portals] OFF;
    END

DROP TABLE [dbo].[Portals];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Portals]', N'Portals';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
